version: 2
updates:
  # fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - driule
    assignees:
      - driule
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope